apiVersion: v1
kind: Service
metadata:
  name: studenttaskmanager-service
  labels:
    app: studenttaskmanager
spec:
  selector:
    app: studenttaskmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer