apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: YWRtaW4=          # base64 encoded value of 'admin'
  password: cGFzc3dvcmQxMjM=  # base64 encoded value of 'password123'